apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  namespace: prediction-api
  labels:
    app: prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
      - name: prediction-api
        image: prediction-api:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: FLASK_ENV
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: REDIS_DB
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: MODEL_PATH
        - name: LOOKBACK_WINDOW
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: LOOKBACK_WINDOW
        - name: DATA_PATH
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: DATA_PATH
        - name: GUNICORN_WORKERS
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: GUNICORN_WORKERS
        - name: GUNICORN_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: GUNICORN_TIMEOUT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: prediction-api-config
              key: LOG_LEVEL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: prediction-api-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-api-service
  namespace: prediction-api
  labels:
    app: prediction-api
spec:
  selector:
    app: prediction-api
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: prediction-api
spec:
  accessModes:
    - ReadWriteMany  # For shared model storage
  resources:
    requests:
      storage: 2Gi
